name: DockHealth Api
on: [push]

env:
  DOCK_HEALTH_API: ${{ secrets.DOCK_HEALTH_API }}
  DOCK_HEALTH_KEY: ${{ secrets.DOCK_HEALTH_KEY }}
  DOCK_HEALTH_SECRET: ${{ secrets.DOCK_HEALTH_SECRET }}
  DOCK_HEALTH_URL: ${{ secrets.DOCK_HEALTH_URL }}
  DOCK_USER: ${{ secrets.DOCK_USER }}
  DOCK_ORG: ${{ secrets.DOCK_ORG }}
  DOCK_HEALTH_AUTH_URL: ${{ secrets.DOCK_HEALTH_AUTH_URL }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true
      - uses: actions/checkout@v3
      - name: Build and test with rspec
        run: |
          gem install bundler
          bundle install
          bundle exec rspec spec
